name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Execute uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-snake.svg

      - name: Commit and push the result
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-snake.svg
          git commit -m 'Generate snake animation'
          git push
